### ISSUE TITLE
Visual Studio deletes common precompiled headers :(

### ISSUE THREAD

**Issue by mick-p1982** [nanoant/CMakePCHCompiler#12]
I've made many improvements to this module (I need to apply it to a real world project) only to in the final moment be thwarted seemingly by VS itself:

https://developercommunity.visualstudio.com/content/problem/15171/shared-precompiled-header-gots-deleted-during-buil.html

This is not my bug-report, but I've found a few of these around, and I think it's worth logging with this effort. I would make this "issue" under my fork, but GitHub either won't let me make an issue on my own repository or on forks.

It seems as if this issue has been around since VS2010. Going by accounts. To work around it the REUSE feature can't be used, and some other strategy will be required. 

From the link: (**Shared precompiled header gots deleted during build.**)[sic]
> I use shared static library project for building precompiled header, which is shared among most of other projects. When dependant projects start build the referenced .pch file got deleted due to lines 249-250 in Microsoft.CppCommon.targets file, which are trying to prevent compile warnings. But in my I case I would prefer disable certain warnings instead of loosing ability to use common pch. To reproduce the issue I attached a simple solution with such configuration. How can I workaround this issue, without disabling debug info in my projects?

**Comment by nanoant** [comment]
Oh now I found this one, let's continue discussion at #21.
