### ISSUE TITLE
TYPE is c++-header? What is this for anyway?

### ISSUE THREAD

**Issue by mick-p1982** [nanoant/CMakePCHCompiler#22]
I was just reading the README. I think it should also say that the default for TYPE is `c-header` under C. 

But, I also wonder what changing this can achieve, and if that should be explained by the README file?

**Comment by nanoant** [comment]
To be honest that is really good question and I cannot remember why I did leave the `TYPE` there in place :)
And yes you are completely right that if we mention `c++-header` in README we should also mention that it is `c-header` for `C` and that we define `CPCH` for plain-C projects too.

**Comment by nanoant** [comment]
I removed the mention of this parameter in 5b56269e0d22576d1559b8de494ca99c94458748. So I will close the issue here.
