### ISSUE TITLE
Wrong C++ standard - GNU extensions enabled in PCH file but disabled in CMake

### ISSUE THREAD

**Issue by martinhanzik** [nanoant/CMakePCHCompiler#23]
On macOS, using brew llvm, it's setting the -std=gnu++17 flag instead of the -std=c++17 flag I use for the rest of the project and I get the following error when it actually uses the pch: 'GNU extensions was enabled in PCH file but is currently disabled'.

**Comment by nanoant** [comment]
I have spent a while investigating this and this is indeed pretty tricky to carry `CXX_STANDARD` to PCH target. The problem that current CMake implementation for selecting C++ standard is pretty complicated and uses combination of `CMAKE_CXX??_STANDARD/EXTENSION_COMPILE_OPTION` compiler defined variables and custom dedicated code of `cmLocalGenerator::AddCompilerRequirementFlag` that adds these flags.

I tried to convince CMake to add these for PCH target too adding relevant entries in `CMakeCXXPCHCompiler.cmake.in` as it check if the compiler has `CMAKE_ + lang + _STANDARD_DEFAULT` defined, but it seems to be not enough.

FYI current baked in solution provided by @mick-p1982 simply bakes `-std=gnu++<STD>` rather using the CMakes built-in complicated C++ standard flags handling. That is why you get wrong standard. For now you can simply replace `-std=gnu++` with `-std=c++` and I believe this should do the job for you.

I am rather short on time for this project and already spend couple of hours yesterday, so any help would be appreciated.

**Comment by drizt** [comment]
Hm. I think maybe it is possible to use `CMAKE_EXPORT_COMPILE_COMMANDS` to get exact compile command? It will work only with Ninja and Unix Makefile generators. I tried it with my project so output:

``` json
[
{
  "directory": "/home/taurus/develop/torrent-file-editor/release-qt5",
  "command": "/usr/lib64/ccache/g++  -DHAVE_QT5 -DQT_CORE_LIB -DQT_GUI_LIB -DQT_NO_CAST_FROM_ASCII -DQT_NO_DEBUG -DQT_WIDGETS_LIB -I../ -I. -isystem /usr/include/qt5 -isystem /usr/include/qt5/QtCore -isystem /usr/lib64/qt5/mkspecs/linux-g++ -isystem /usr/include/qt5/QtGui -isystem /usr/include/qt5/QtWidgets   -std=c++11 -Wall -Wextra -pedantic -Werror -Wno-error=cpp -O2 -DNDEBUG   -fPIC -std=gnu++11 -o CMakeFiles/torrent-file-editor.dir/application.cpp.o -c /home/taurus/develop/torrent-file-editor/application.cpp",
  "file": "/home/taurus/develop/torrent-file-editor/application.cpp"
}
]
```

**Comment by mick-p1982** [comment]
If there is no way to detect it with CMake then there has to be a parameter added to module's commands.
