### ISSUE TITLE
Doesn't work with multiple language targets.

### ISSUE THREAD

**Issue by smilediver** [nanoant/CMakePCHCompiler#27]
It doesn't work when target mixes multiple languages (C, C++, Objective-C, ObjectiveC++). target_precompiled_header should generate a separate header for each language, or use the pch only for the language it was compiled for.

**Comment by embeddedteam103** [comment]
Ran into the same issue (am a new user).
A simpler approach would be only support this if `TYPE` argument was provided explicitly and generate the pch only for this specific type.

This is very straight forward to implement:
After https://github.com/nanoant/CMakePCHCompiler/blob/6bab2842e7829333e6f79e44783af7d6b0895ab9/CMakePCHCompiler.cmake#L76
add
```
if(header_type STREQUAL c-header)
    set(lang "C")
elseif(header_type STREQUAL c++-header)
    set(lang "CXX")
endif()
```

But I don't have any experience with this library so take this with a grain of salt.
[I'm fiddling with making this library work for my project, and this is one of several issues we have, so I can't comment explicitly "this works for me"]

**Comment by nanoant** [comment]
Hi @smilediver & @embeddedteam103,
Can you please provide minimal example of `CMakeLists.txt` that your want to use for mixed-lang scenario, where either `CXX` or `C` is language that you want have PCH for, but it does break compilation for other language files. I can try to work on something.

I agree that we should add precompiled header compiler flags to only one (`CXX` or `C`) language sources without affecting other languages in the target.

As for separate (multiple) precompiled headers for multiple languages within single target, I don't feel convinced why would someone want multiple-PCH in a single target in the first place.

Moreover, currently we support C++ & C only as I override `C` and `CXX` compiler definitions, so having precompiled header for other languages requires having working PCH defined for them first, i.e. `CMake<LANG>PCHCompiler.cmake.in`

**Comment by smilediver** [comment]
> As for separate (multiple) precompiled headers for multiple languages within single target, I don't feel convinced why would someone want multiple-PCH in a single target in the first place.

If you have a header like this:

    #ifdef __cplusplus
        #define FOO 1
    #else
        #define FOO 2
    #endif

and you compile PCH for C++, then this PCH would fail when including for C. So either CMakePCHCompiler needs to generate a separate header for each language and use those (since it already generates headers), or it needs to precompile this header into separate PCH for each language.

**Comment by nanoant** [comment]
@smilediver I understand. However still I don't see why you want to have pre-compiled header and mix C and C++ withing single target. You can always split your plain C into kind of `core` and C++ into `hilevel` separate static library targets with current implementation. Like I said I don't feel convinced to add extra code complication for a feature that does not bring clear benefit.

**Comment by mick-p1982** [comment]
> 
> 
> Hi @smilediver & @embeddedteam103,
> Can you please provide minimal example of `CMakeLists.txt` that your want to use for mixed-lang scenario, where either `CXX` or `C` is language that you want have PCH for, but it does break compilation for other language files. I can try to work on something.
> 
> I agree that we should add precompiled header compiler flags to only one (`CXX` or `C`) language sources without affecting other languages in the target.
> 
> As for separate (multiple) precompiled headers for multiple languages within single target, I don't feel convinced why would someone want multiple-PCH in a single target in the first place.
> 
> Moreover, currently we support C++ & C only as I override `C` and `CXX` compiler definitions, so having precompiled header for other languages requires having working PCH defined for them first, i.e. `CMake<LANG>PCHCompiler.cmake.in`

I use multiple in my project... just break it up into multiple objects. In this case, sort your C and C++ files into two targets, and then link them. Problem solved.

I should add (caution) that if you are using this for development work you're doing it wrong. Don't use CMake for that. Use this to deploy your software via sources to unknown platforms. Use this if you feel like your build times are egregious for your end-users building your software. Don't use this (or CMake) to do dev work. Or, take the time to build a proper project for the environment you are principally working in.

**Comment by nanoant** [comment]
Sorry I am marking it as won't fix.

Like @mick-p1982 said you may split `C` and `C++` into separate targets and workaround PCH generation this way, so it essentially you can reach your objective, but you need to slightly alter your project definition.

**Comment by smilediver** [comment]
> However still I don't see why you want to have pre-compiled header and mix C and C++ withing single target.
> you may split C and C++ into separate targets

I can't split the project, because target setup is done by a third party CMake scripts. Also it's a pretty common practice to mix languages. For example, any portable project targeting iOS and other platforms must mix C/C++ with Objective-C/Objective-C++.

**Comment by nanoant** [comment]
@smilediver I know that there is practice to mix languages to provide support for multiple platforms. But in most of the case 95% code-base is a single language and I can understand that you want precompiled header for that.

The platform specific code is usually really thin (e.g. Qemu), and because of that lack of precompiled header for 2 source files from out of 1000 does not play huge role. Otherwise, if the platform specific code is big, then from software architecture standpoint it should be independent target library. etc. etc.

Anyway with a8aaf6a523a4d3ba47922913c14f18193a982063 CMakePCHCompiler supports precompiled header for mixed language targets, but only for one language, not all. And because limited time and resources this will not change unless someone proposes PR that does not make CMakePCHCompiler too complicated.

Also, your usage of 3rd party CMake scripts that disallow you splitting platform specific code into separate target libraries does not really justifies adding extra complexity to CMakePCHCompiler.

**Comment by mick-p1982** [comment]
> 
> 
> > However still I don't see why you want to have pre-compiled header and mix C and C++ withing single target.
> > you may split C and C++ into separate targets
> 
> I can't split the project, because target setup is done by a third party CMake scripts. Also it's a pretty common practice to mix languages. For example, any portable project targeting iOS and other platforms must mix C/C++ with Objective-C/Objective-C++.

You don't "split the project" (into multiple projects) ... you just stake out more "targets" under the umbrella of the same project. Like every static-library is a target. CMake also has a more generic form it calls OBJECT that is what the precompiled headers use if I'm not mistaken. It's complicated, but everything CMake is thus.
