### ISSUE TITLE
Compile your code with -fPIC or -fPIE

### ISSUE THREAD

**Issue by drizt** [nanoant/CMakePCHCompiler#34]
I try to build my project with Travis. But with Qt5 there is such [error](https://travis-ci.org/torrent-file-editor/torrent-file-editor/jobs/526197640#L703). On my local machine no any problems. Travis has CMake 3.9.2.

**Comment by nanoant** [comment]
There some explicit handling for `-fPIC` introduced by @mick-p1982 and `POSITION_INDEPENDENT_CODE` property is not carried over to PCH target for some reason.

@mick-p1982 Do you remember what was the issue with `POSITION_INDEPENDENT_CODE`?

**Comment by nanoant** [comment]
This is somewhat similar (but not duplicate) to #23. We need to ensure that we properly copy `CMAKE_CXX_COMPILE_OPTIONS_PIC` to `CXXPCH` in order to make PIC generation working for PCH.
I try to work on it in near future.

**Comment by mick-p1982** [comment]
The high-level feature CMake offers for PIC just don't get processed normally... CMake must add it later in the pipeline. I've never heard of PIE; but I'm sure it can be added. I'm not offering. The PIC variable is injected near the bottom of the main script file.

I should add that the feature isn't about setting the "-fPIC" flag manually. It's about the platform-independent feature provided by CMake.

**Comment by nanoant** [comment]
Fixed in e17969b
