### ISSUE TITLE
Improve documentation about auto-include "pch.h"

### ISSUE THREAD

**Issue by drizt** [nanoant/CMakePCHCompiler#35]
Atm it's not obviously that precompiled header will be autoincluded with `-include` compilation flag. I found it's in README but first I inserted `#include "pch.h"` in all my project files. So please add in **Example** section also main.cpp and pch.h files to show how it exactly works. Or maybe new example dir in repo with full example which everyone can compile and learn.

**Comment by nanoant** [comment]
IMHO you should still `#include "prefix.h"` in all your source files to ensure they remain portable and compilable regardless if your build system, selected compiler, etc. support precompiled headers or not.

The internal behavior of `-include` is there to ensure that pre-compiled version of `prefix.h` becomes first compile unit, and when compiler encounters `#include "prefix.h"` in your source it will be not parsed again from its textual form (assuming include guards).

I am not convinced that README should be extended with whether you should or should not `#include "prefix.h"`. I believe it is not CMakePCHCompiler's task to teach user what are pre-compiled headers and how to use them.
