### ISSUE TITLE
Comparison between CMakePCHCompiler and CMake's new implementation

### ISSUE THREAD

**Issue by dpacbach** [nanoant/CMakePCHCompiler#43]
Looks like CMake developers have just added PCH support and it should appear version 3.16+ (from what it looks like).  How does their implementation compare with using CMakePCMCompiler?    Which do you recommend?

**Comment by nanoant** [comment]
@dpacbach I recommend the native 3.16 implementation, and as the README was stating almost from the very beginning, that native implementation is only sensible way to go.
As native support will be soon in stable release this project is now considered obsolete.
